# Generated by Django 3.1.2 on 2020-11-10 00:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_auto_20201110_0617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingDetails',
            new_name='BillingDetail',
        ),
    ]
