# Generated by Django 3.1.2 on 2020-11-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20201112_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcustomer',
            name='name',
            field=models.CharField(default='Happy Guest', max_length=50),
        ),
    ]
