# Generated by Django 3.1.2 on 2020-10-30 14:32

from django.db import migrations, models
import merchandise.models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=merchandise.models.upload_image),
        ),
    ]
