# Generated by Django 3.1.2 on 2020-11-02 16:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('merchandise', '0008_product_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
