# Generated by Django 3.1.2 on 2020-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0009_auto_20201102_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Accesories', 'Accesories')], default='Miscellaneous', max_length=120),
        ),
    ]
