# Generated by Django 3.1.2 on 2020-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0010_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Accesories', 'Accesories'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=120),
        ),
    ]
