# Generated by Django 3.1.2 on 2020-11-21 12:22

from django.db import migrations, models
import merchandise.models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0012_product_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_small_image1',
            field=models.ImageField(blank=True, null=True, upload_to=merchandise.models.upload_image),
        ),
        migrations.AddField(
            model_name='product',
            name='product_small_image2',
            field=models.ImageField(blank=True, null=True, upload_to=merchandise.models.upload_image),
        ),
        migrations.AddField(
            model_name='product',
            name='product_small_image3',
            field=models.ImageField(blank=True, null=True, upload_to=merchandise.models.upload_image),
        ),
        migrations.AddField(
            model_name='product',
            name='product_small_image4',
            field=models.ImageField(blank=True, null=True, upload_to=merchandise.models.upload_image),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=120),
        ),
    ]
