# Generated by Django 3.1.2 on 2020-11-13 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_auto_20201110_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=300)),
                ('line_2', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=150)),
                ('postalcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=150)),
                ('billing_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=300)),
                ('line_2', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=150)),
                ('postalcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=150)),
                ('billing_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
