# Generated by Django 3.1.2 on 2020-11-13 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
